[2024-02-03T23:33:06.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sf_data_upload.sf311_add_coord_task scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-03T23:33:06.561+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sf_data_upload.sf311_add_coord_task scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-03T23:33:06.563+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-02-03T23:33:06.572+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): sf311_add_coord_task> on 2024-02-02 00:00:00+00:00
[2024-02-03T23:33:06.579+0000] {standard_task_runner.py:60} INFO - Started process 56 to run task
[2024-02-03T23:33:06.582+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sf_data_upload', 'sf311_add_coord_task', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/sf311_data_upload_dag.py', '--cfg-path', '/tmp/tmpa4pzlp88']
[2024-02-03T23:33:06.586+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask sf311_add_coord_task
[2024-02-03T23:33:06.623+0000] {task_command.py:423} INFO - Running <TaskInstance: sf_data_upload.sf311_add_coord_task scheduled__2024-02-02T00:00:00+00:00 [running]> on host 99c4b1b0af99
[2024-02-03T23:33:06.750+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sf_data_upload' AIRFLOW_CTX_TASK_ID='sf311_add_coord_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-02-03T23:33:09.210+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=683+12TH+AVE%2C+SAN+FRANCISCO%2C+CA%2C+94118&format=json&limit=1
[2024-02-03T23:33:13.006+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=526+NATOMA+ST%2C+SAN+FRANCISCO%2C+CA%2C+94103&format=json&limit=1
[2024-02-03T23:33:15.863+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=1492+EGBERT+AVE%2C+SAN+FRANCISCO%2C+CA%2C+94124&format=json&limit=1
[2024-02-03T23:33:26.225+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=4145+21ST+ST%2C+SAN+FRANCISCO%2C+CA%2C+94114&format=json&limit=1
[2024-02-03T23:33:59.708+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=330+BYXBEE+ST%2C+SAN+FRANCISCO%2C+CA%2C+94132&format=json&limit=1
[2024-02-03T23:34:03.208+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=3960+IRVING+ST%2C+SAN+FRANCISCO%2C+CA%2C+94122&format=json&limit=1
[2024-02-03T23:34:07.744+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=271+MONTEREY+BLVD%2C+SAN+FRANCISCO%2C+CA%2C+94131&format=json&limit=1
[2024-02-03T23:34:31.042+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=647+CLAY+ST%2C+SAN+FRANCISCO%2C+CA%2C+94111&format=json&limit=1
[2024-02-03T23:34:32.515+0000] {python.py:201} INFO - Done. Returned value was:      service_request_id  requested_datetime  ...        lat        long
0              17841168 2024-02-02 01:29:22  ...  37.760777 -122.434918
1              17841162 2024-02-02 01:18:09  ...  37.786462 -122.395753
2              17841161 2024-02-02 01:18:02  ...  37.776938 -122.472381
3              17841158 2024-02-02 01:13:00  ...  37.788118 -122.418045
4              17841157 2024-02-02 01:12:00  ...  37.786300 -122.414555
..                  ...                 ...  ...        ...         ...
995            17838519 2024-02-01 11:08:00  ...  37.778366 -122.402695
996            17838518 2024-02-01 11:08:00  ...  37.746839 -122.414077
997            17838516 2024-02-01 11:07:38  ...  37.763809 -122.471529
998            17838515 2024-02-01 11:07:00  ...  37.733290 -122.444328
999            17838507 2024-02-01 11:05:00  ...   0.000000    0.000000

[1000 rows x 21 columns]
[2024-02-03T23:34:32.583+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sf_data_upload, task_id=sf311_add_coord_task, execution_date=20240202T000000, start_date=20240203T233306, end_date=20240203T233432
[2024-02-03T23:34:32.624+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-03T23:34:32.643+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
